### ISSUE TITLE
Preview image not reactive to document change.

### ISSUE THREAD

**Issue by tnordberg** [yogiben/meteor-autoform-file#57]
When the `doc` parameter of the autoForm changes, child afQuickFields should update accordingly. However, the fileUpload preview image does not react. Clicking the Reset button seems to force a refresh and the expected preview image is displayed. Is this as intended?

In the following example, the `title` (text input) will correctly update when the`activeSlide` helper changes, but the `background` (fileUpload) preview image does not change until the Reset button is clicked. 
```html
{{#autoForm id="form_editSlide" collection="Slides" doc=activeSlide}}
  {{> afQuickField name="title"}}
  {{> afQuickField name="background"}}
  <button type="submit" class="btn btn-primary">Submit</button>
  <button type="reset" class="btn btn-default">Reset</button>
{{/autoForm}}
```

**Comment by kristijanbambir** [comment]
+1
And I can say that this issue was not present in version 0.2.5.

**Comment by mpowaga** [comment]
This should be fixed in 0.3.0.

**Comment by ralph-fuechtenkort** [comment]
I still have the same problem on 0.4.0 even with the reset button. Any comment on this?

**Comment by caffpain** [comment]
I'm using yogiben:autoform-file@0.4.2 and still have this problem.  Anyone got a workaround?

**Comment by kukagg** [comment]
+1, experienced just now.

Any workaround or ideas?

UPD: Seems like https://github.com/yogiben/meteor-autoform-file/pull/91 is fixing this. Care to accept?
