### ISSUE TITLE
Upload form does not upload the image for me unless I pick the file the 2nd time.

### ISSUE THREAD

**Issue by VansonLeung** [yogiben/meteor-autoform-file#74]
I am using version 0.3.0. Now I need to open file picker 2 times, pick the 2nd time the file and then it would show loading bar & upload the file for me. The 1st time open the file-picker after the autoform is initiated, it never works.

**Comment by limingth** [comment]
Yes. I got the same problem.  and I also found this

![image](https://cloud.githubusercontent.com/assets/1249369/10899568/f7cf2c88-8210-11e5-95cc-4b27bed75da8.png)

1.0.1 works find for me :+1:  and now 0.3.0 is buggy  :-1:

**Comment by VansonLeung** [comment]
And I could not downgrade to 1.0.1 / 0.3.0- because they conflicts on the 'less' versions of my other plugins

**Comment by limingth** [comment]
Yes. I just set up a clone of this repo and revert back to this commit

**Comment by Xiangshen-Meng** [comment]
Hi, if you to use it in project right now,  try the my temp meteor package.
https://github.com/Xiangshen-Meng/meteor-autoform-file

For local development, fork this repo and install locally maybe is good idea.

**Comment by limingth** [comment]
@Xiangshen-Ment  

meteor add shinn:autoform-file  works fine!  You really fix the bug  :+1: :+1: :+1:

**Comment by Xiangshen-Meng** [comment]
@limingth actually I just set some of the code back, and I am still waiting for the bugfix.
:smile:

**Comment by limingth** [comment]
If you have post 1 hour earlier, I wouldn't take half an hour to fix this bug myself.

**Comment by VansonLeung** [comment]
@limingth @Xiangshen-Meng thank you all!

**Comment by isubasti** [comment]
@limingth @Xiangshen-Meng I'm using the github version of this package and it is working just fine as the bug that appears on the atmospherejs version had already been fixed by this specific commit https://github.com/yogiben/meteor-autoform-file/commit/fc3ca05344f5a17c41fb7e7f96a6397d84cefae9 .

**Comment by Xiangshen-Meng** [comment]
@isubasti Thanks! Waiting for the atmosphere :smile:

**Comment by limingth** [comment]
@isubasti  You are right.  I've tried to test the newest code and it works. 
Maybe the one who fixed the bug has no right to meteor publish it. :8ball: 
I published a temp package for ```meteor add maodouio:autoform-file```

**Comment by Xiangshen-Meng** [comment]
@isubasti by the way, I still have a bug when using image preview.
Is that my problem?

**Comment by limingth** [comment]
check this, hope it helps
```
  picture: {
    type: String,
    optional: false,
    label: 'Upload',
    autoform: {
      afFieldInput: {
        type: 'fileUpload',
        collection: 'Images',
        previewTemplate: 'myFilePreview',
        label: 'choose picture',
      }
    }
  },

<template name="myFilePreview">
  <!-- <a href="{{file.url}}">{{file.original.name}}</a> -->
  <img src="{{file.url}}" alt="{{file.original.name}}" width="150px;"/>
</template>
```

**Comment by isubasti** [comment]
@Xiangshen-Meng not to sure about the built-in image preview since I'm using a custom template for mine but technically it should work

**Comment by Xiangshen-Meng** [comment]
@isubasti @limingth Thanks! It was great help. Seems the built-in image preview does not work well.

**Comment by obiwarn** [comment]
Hello. Same problem here. Im always have to select another image first.

**Comment by VansonLeung** [comment]
@limingth @Xiangshen-Meng @isubasti  Thanks for all your help! Will check it out now

**Comment by corv89** [comment]
Thanks for fixing this everyone. Unfortunately the fix (https://github.com/yogiben/meteor-autoform-file/commit/85ace6826a9168c16d71539caea226ef5ac19496) still hasn't been pushed to Atmosphere.

**Comment by THPubs** [comment]
@Xiangshen-Meng Thanks a lot for the package you released. It really fixed the issue! But there's a small problem. When I try to edit a page with an uploaded image, the image doesn't show up. But it is in the database attached to the page and I have the right publications in place. When I add the original package, it works. When I add autopublish, then also it works! What might be the issue?

**Comment by THPubs** [comment]
Thanks for the fix! I'm testing it out... seems to be working for now! Finally! :-)

**Comment by jebarjonet** [comment]
I also have this issue now with the new version 0.4.2. Following this issue : https://github.com/yogiben/meteor-autoform-file/issues/81 now when I remove an existing image (when I edit an object) then I select a new one, the old one is displayed again. I have to remove it again then chose the new image I want to have, and then it works.

When it is on a blank form (without any image to remove) it works well.

**Comment by THPubs** [comment]
@jebarjonet Yea I also noticed that issue

**Comment by Obiwarn** [comment]
@jebarjonet indeed. same here.
